config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"

  scope module: :public do
    get   'about'                   => "homes#about"
    get   'tos'                     => "homes#tos"
    get   'mypage'                  => 'users#mypage', as: "mypage"
    get   'mypage/edit'             => 'users#edit', as: "mypage_edit"
    patch 'mypage'                  => 'users#update'
    get   'unsubscribe'             => 'users#unsubscribe', as: "unsubscribe"
    patch 'withdrow'                => 'users#withdrow', as: "withdrow"
    get   "mypage/friends"          => "relationships#friends", as: "friends"
    get   "mypage/follow_requests"  => "relationships#follow_requests", as: "follow_requests"
    resources :users, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create]
    resources :notifications, only: [:index, :destroy]

    resources :balloons,            only: [:new, :create, :show, :update, :destroy] do
      resource  :favorites,         only: [:create, :destroy]
      resource  :balloon_stickers,  only: [:create]
      resources :balloon_comments,  only: [:create, :destroy]
      resource  :reports,           only: [:create]
    end
    get 'searches/search'
    get 'searches/balloons_search'
    post "searches/user_search"
  end

  namespace :admin do
    get 'top' => "homes#top"
    resources :users,     only: [:index, :show, :update]
    resources :balloons,  only: [:show, :destroy] do
      resources :balloon_comments, only: [:destroy]
    end
    resources :stickers,  only: [:index, :edit, :create, :update, :destroy]
  end

end

app/models/sticker.rb
class Sticker < ApplicationRecord

  has_many :balloon_stickers, dependent: :destroy

  validates :message, presence: true

end

app/controllers/admin/stickers_controller.rb
class Admin::StickersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_sticker, only: [:edit, :update, :destroy]

  def index
    @stickers = Sticker.all
    @sticker = Sticker.new
  end

  def create
    @sticker = Sticker.new(sticker_params)
    if @sticker.save
      redirect_to admin_stickers_path, notice: "新規ステッカーを登録しました。"
    else
      @stickers = Sticker.all
      render :index
    end
  end

  def edit
  end

  def update
    if @sticker.update(sticker_params)
      redirect_to admin_stickers_path, notice: "ステッカーを編集しました。"
    else
      render :edit, alert: "編集に失敗しました。"
    end
  end

  def destroy
    @sticker.destroy
    redirect_to admin_stickers_path, notice: "ステッカーを削除しました。"
  end

  private

  def sticker_params
    params.require(:sticker).permit(:message)
  end

  def ensure_sticker
    @sticker = Sticker.find(params[:id])
  end

end

app/helpers/admin/stickers_helper.rb
module Admin::StickersHelper
end

app/views/admin/stickers/edit.html.erb
<article class="container text-center">
  <%= render 'layouts/errors', obj: @sticker %>
  <h2>ステッカー編集</h2>
  <div class="col-4 mx-auto my-4">
    <%= form_with model: @sticker, url: admin_sticker_path(@sticker), method: :patch, local: true do |f| %>
      <div>
        <%= f.label "褒めステッカー", class: "form-label" %>
      </div>
      <div>
        <%= f.text_field :message, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "更新", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</article>

app/views/admin/stickers/index.html.erb
<article class="container text-center">
  <%= render 'layouts/errors', obj: @sticker %>
  <h2>ステッカー一覧・追加</h2>
  <div class="col-4 mx-auto my-4">
    <%= form_with model: @sticker, url: admin_stickers_path, local: true do |f| %>
      <div>
        <%= f.label "褒めステッカー", class: "form-label" %>
      </div>
      <div>
        <%= f.text_field :message, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "更新", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

  <div class="">
    <table class="table">
      <thead>
        <tr  class="table-secondary text-center">
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @stickers.each do |sticker| %>
          <tr>
            <td><%= sticker.message %></td>
            <td>
              <%= link_to '編集', edit_admin_sticker_path(sticker), class: "btn btn-info border" %>
              <%= link_to '削除', admin_sticker_path(sticker), method: :delete, class: "ml-4 btn btn-danger border", data: { confirm: "ステッカーを削除しますか？" }%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</article>