config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"

  scope module: :public do
    get   'about'                   => "homes#about"
    get   'tos'                     => "homes#tos"
    get   'mypage'                  => 'users#mypage', as: "mypage"
    get   'mypage/edit'             => 'users#edit', as: "mypage_edit"
    patch 'mypage'                  => 'users#update'
    get   'unsubscribe'             => 'users#unsubscribe', as: "unsubscribe"
    patch 'withdrow'                => 'users#withdrow', as: "withdrow"
    get   "mypage/friends"          => "relationships#friends", as: "friends"
    get   "mypage/follow_requests"  => "relationships#follow_requests", as: "follow_requests"
    resources :users, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create]
    resources :notifications, only: [:index, :destroy]

    resources :balloons,            only: [:new, :create, :show, :update, :destroy] do
      resource  :favorites,         only: [:create, :destroy]
      resource  :balloon_stickers,  only: [:create]
      resources :balloon_comments,  only: [:create, :destroy]
      resource  :reports,           only: [:create]
    end
    get 'searches/search'
    get 'searches/balloons_search'
    post "searches/user_search"
  end

  namespace :admin do
    get 'top' => "homes#top"
    resources :users,     only: [:index, :show, :update]
    resources :balloons,  only: [:show, :destroy] do
      resources :balloon_comments, only: [:destroy]
    end
    resources :stickers,  only: [:index, :edit, :create, :update, :destroy]
  end

end

app/models/balloon.rb
class Balloon < ApplicationRecord
  belongs_to :user

  has_many :favorites,        dependent: :destroy
  has_many :reports,          dependent: :destroy
  has_many :balloon_comments, dependent: :destroy
  has_many :balloon_stickers, dependent: :destroy
  has_many :balloon_tags,     dependent: :destroy
  has_many :tags, through: :balloon_tags

  has_one :notification, as: :notifiable, dependent: :destroy

  has_one_attached :balloon_image

  scope :where_user_active, -> { joins(:user).where(users: { is_active: true }) }
  scope :where_user_delete, -> { joins(:user).where(users: { is_active: false }) }

  enum color_status: {
    white:    1,
    black:    2,
    red:      3,
    orange:   4,
    yellow:   5,
    grass:    6,
    green:    7,
    water:    8,
    blue:     9,
    wisteria: 10,
    purple:   11,
    pink:     12
  }

  with_options presence: true do
    validates :user_id
    validates :content, length: { in: 1..200 }
    validates :color_status
  end

  def convert_balloon_image(size)
    balloon_image.variant( resize: size ).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/admin/balloons_controller.rb
class Admin::BalloonsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_balloon
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def show
    @user = User.find(@balloon.user_id)
  end

  def destroy
    @balloon.destroy
    redirect_to admin_top_path, notice: "バルーンを削除しました。"
  end

  private

  def ensure_balloon
    @balloon = Balloon.find(params[:id])
  end

  def record_not_found
    redirect_to admin_top_path, alert: "存在しないページです。"
  end

end

app/helpers/admin/balloons_helper.rb
module Admin::BalloonsHelper
end

app/views/admin/balloons/_index.html.erb
<div class="row">
  <div class="col mx-auto">
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th>会員名</th>
          <th>本文</th>
          <th>報告数</th>
        </tr>
      </thead>
      <tbody>
        <% balloons.each do |balloon| %>
          <tr>
            <td><%= link_to find_user(balloon).name, admin_user_path(find_user(balloon)) %></td>
            <td><%= link_to balloon.content.truncate(20), admin_balloon_path(balloon) %></td>
            <td><%= balloon.reports.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/balloons/show.html.erb
<article class="layout pb-5">
  <div class="balloon-frame-show">
    <div class="card balloon balloon-<%= @balloon.color_status %>">
      <%= image_tag @balloon.convert_balloon_image("300"), class: "balloon-image" if @balloon.balloon_image.attached? %>
      <div class="balloon-content"><%= simple_format(h(@balloon.content)) %></div>
      <div class="balloon-tag">
        <% @balloon.tags.each do |tag| %>
          <div class="tag-box"><%= "##{tag.name}" %></div>
        <% end %>
      </div>
    </div>
    <div class="balloon-created-time">投稿日時: <%= l @balloon.created_at %></div>
    <div class="balloon-user-id">ID: <%= @user.public_uid %></div>
    <%= link_to "削除", admin_balloon_path(@balloon), method: :delete, class: "btn btn-danger balloon-delete border", local: true, data: { confirm: "バルーンを削除しますか？" } %>

    <div class="balloon-reports-count">報告数: <%= @balloon.reports.count %></div>
  </div>

  <h3>コメント</h3>

  <div class="mx-auto">
    <table class="table">
      <tr>
        <th>名前</th>
        <th>コメント</th>
        <th></th>
      </tr>
      <% @balloon.balloon_comments.each do |balloon_comment| %>
        <tr>
          <td>
            <div>
              <%= balloon_comment.user.name %>
            </div>
          </td>
          <td>
            <%= balloon_comment.comment %>
          </td>
          <td width="10%">
            <%= link_to admin_balloon_balloon_comment_path(balloon_comment.balloon, balloon_comment), method: :delete, data: { confirm: 'コメントを削除しますか？' }, class: "btn btn-sm btn-danger" do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

</article>