config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"

  scope module: :public do
    get   'about'                   => "homes#about"
    get   'tos'                     => "homes#tos"
    get   'mypage'                  => 'users#mypage', as: "mypage"
    get   'mypage/edit'             => 'users#edit', as: "mypage_edit"
    patch 'mypage'                  => 'users#update'
    get   'unsubscribe'             => 'users#unsubscribe', as: "unsubscribe"
    patch 'withdrow'                => 'users#withdrow', as: "withdrow"
    get   "mypage/friends"          => "relationships#friends", as: "friends"
    get   "mypage/follow_requests"  => "relationships#follow_requests", as: "follow_requests"
    resources :users, only: [:show] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create]
    resources :notifications, only: [:index, :destroy]

    resources :balloons,            only: [:new, :create, :show, :update, :destroy] do
      resource  :favorites,         only: [:create, :destroy]
      resource  :balloon_stickers,  only: [:create]
      resources :balloon_comments,  only: [:create, :destroy]
      resource  :reports,           only: [:create]
    end
    get 'searches/search'
    get 'searches/balloons_search'
    post "searches/user_search"
  end

  namespace :admin do
    get 'top' => "homes#top"
    resources :users,     only: [:index, :show, :update]
    resources :balloons,  only: [:show, :destroy] do
      resources :balloon_comments, only: [:destroy]
    end
    resources :stickers,  only: [:index, :edit, :create, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balloon.rb
class Balloon < ApplicationRecord
  belongs_to :user

  has_many :favorites,        dependent: :destroy
  has_many :reports,          dependent: :destroy
  has_many :balloon_comments, dependent: :destroy
  has_many :balloon_stickers, dependent: :destroy
  has_many :balloon_tags,     dependent: :destroy
  has_many :tags, through: :balloon_tags

  has_one :notification, as: :notifiable, dependent: :destroy

  has_one_attached :balloon_image

  scope :where_user_active, -> { joins(:user).where(users: { is_active: true }) }
  scope :where_user_delete, -> { joins(:user).where(users: { is_active: false }) }

  enum color_status: {
    white:    1,
    black:    2,
    red:      3,
    orange:   4,
    yellow:   5,
    grass:    6,
    green:    7,
    water:    8,
    blue:     9,
    wisteria: 10,
    purple:   11,
    pink:     12
  }

  with_options presence: true do
    validates :user_id
    validates :content, length: { in: 1..200 }
    validates :color_status
  end

  def convert_balloon_image(size)
    balloon_image.variant( resize: size ).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/balloon_comment.rb
class BalloonComment < ApplicationRecord

  belongs_to :user
  belongs_to :balloon

  has_one :notification, as: :notifiable, dependent: :destroy
  after_create :create_notifications

  validates :comment, presence: true

  private

  def create_notifications
    unless balloon.user == self.user
      Notification.create(notifiable: self, user: balloon.user, action_type: :commented_to_own_balloon)
    end
  end

end

app/models/balloon_sticker.rb
class BalloonSticker < ApplicationRecord

  belongs_to :balloon
  belongs_to :sticker

  validates :quantity, presence: true

end

app/models/balloon_tag.rb
class BalloonTag < ApplicationRecord
  belongs_to :balloon
  belongs_to :tag

  validates :balloon_id, uniqueness: { scope: :tag_id }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true

  has_one :notification, as: :notifiable, dependent: :destroy
  after_create :create_notifications

  private

  def create_notifications
    self.room.user_rooms.each do |user_room|
      next if user_room.user == self.user # 送信者自身には通知しない
      Notification.create(notifiable: self, user: user_room.user, action_type: :direct_message_to_me)
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :balloon

  validates :user_id, uniqueness: {scope: :balloon_id}

end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  enum action_type: { commented_to_own_balloon: 0, followed_me: 1, direct_message_to_me: 2}

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_one :notification, as: :notifiable, dependent: :destroy
  after_create :create_notifications

  validates :follower_id, presence: true
  validates :followed_id, presence: true

  validates :follower_id, uniqueness: { scope: :followed_id }

  private

  def create_notifications
    Notification.create(notifiable: self, user: followed, action_type: :followed_me)
  end

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :balloon

  validates :user_id, uniqueness: {scope: :balloon_id}
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :user_rooms
  has_many :chats
  
end

app/models/sticker.rb
class Sticker < ApplicationRecord

  has_many :balloon_stickers, dependent: :destroy

  validates :message, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :balloon_tags, dependent: :destroy
  has_many :balloons, through: :balloon_tags

  validates :name, length: { in: 1..20 }, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # IDランダム生成
  generate_public_uid column: :public_uid

  def to_param
    public_uid
  end

  validates :name, presence: true, length: { in: 1..10 }

  scope :only_active, -> { where(is_active: true) }

  has_one_attached :profile_image

  has_many :balloons,         dependent: :destroy
  has_many :favorites,        dependent: :destroy
  has_many :balloon_comments, dependent: :destroy
  has_many :reports,          dependent: :destroy
  has_many :user_rooms,       dependent: :destroy
  has_many :chats,            dependent: :destroy
  has_many :rooms,            dependent: :destroy, through: :user_rooms
  has_many :notifications,    dependent: :destroy

  # follow機能
  has_many :active_relationships,  class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships,  source: :followed
  has_many :followers,  through: :passive_relationships, source: :follower

  def get_profile_image
    if profile_image.attached?
      profile_image.variant( resize: "160x160" ).processed
    else
      profile_image = 'no_image.jpg'
    end
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def friends
    followings & followers
  end

  def friends?(other_user)
    active_relationships.find_by(followed_id: other_user.id) && passive_relationships.find_by(follower_id: other_user.id)
  end

  def follow_request?(user, other_user)
    !user.friends?(other_user) && other_user.following?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # フラッシュメッセージの色追加
  add_flash_types :success, :info, :warning, :danger
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def find_user(balloon)
    User.find_by(id: balloon.user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger text-center mx-auto mt-2" style="width: 70%;">
    <ul class="list-unstyled mt-2"><button type="button" class="close" data-dismiss="alert">&times;</button>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success text-center mx-auto mt-2" style="width: 70%;">
    <%= flash[:notice] %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger text-center mx-auto mt-2" style="width: 70%;">
    <%= flash[:alert] %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class="d-flex justify-content-around text-center">
    <% if admin_signed_in? %>
      <div class="bg-secondary col-4">
        <%= link_to "通報一覧", admin_top_path, class: "admin-footer-text" %>
      </div>
      <div class="bg-secondary col-4">
        <%= link_to "会員一覧", admin_users_path, class: "admin-footer-text" %>
      </div>
      <div class="bg-secondary col-4">
        <%= link_to 'ステッカー一覧', admin_stickers_path, class: "admin-footer-text" %>
      </div>
      <% elsif user_signed_in? %>
      <div class="footer-bg">
        <%= link_to searches_search_path do %>
          <div class="footer-icon ">
            <span class="fa-stack">
              <i class="fa-solid fa-user-group"></i>
            </span>
          </div>
          <div class="footer-text">
            友達を探す
          </div>
        <% end %>
      </div>
      <div class="footer-bg">
        <%= link_to new_balloon_path do %>
          <div class="footer-icon ">
            <span class="fa-stack">
              <i class="fa-solid fa-circle-plus"></i>
            </span>
          </div>
          <div class="footer-text">
            新規作成
          </div>
        <% end %>
      </div>
      <div class="footer-bg">
        <%= link_to notifications_path do %>
          <div class="footer-icon ">
            <% if current_user.notifications.where(read: false).exists? %>
              <span class="fa-stack">
                <i class="fa-sharp fa-solid fa-bell"></i>
                <i class="fas fa-circle n-circle fa-stack-1x"></i>
              </span>
            <% else %>
            <span class="fa-stack">
              <i class="fa-sharp fa-solid fa-bell"></i>
            </span>
            <% end %>
          </div>
          <div class="footer-text">
            通知一覧
          </div>
        <% end %>
      </div>
      <div class="footer-bg">
        <%= link_to mypage_path do %>
        <div>
          <span>
            <%= image_tag current_user.get_profile_image, size: "32x32", class: "profile-image mx-auto my-2" %>
          </span>
        </div>
        <div class="footer-text align-items-end">
          マイページ
        </div>
        <% end %>
      </div>
    <% else %>
      <div class="footer-bg">
        <%= link_to searches_search_path do %>
          <div class="footer-icon ">
            <span class="fa-stack">
              <i class="fa-solid fa-user-group"></i>
            </span>
          </div>
          <div class="footer-text">
            友達を探す
          </div>
        <% end %>
      </div>
      <div class="footer-bg">
        <%= link_to new_balloon_path do %>
          <div class="footer-icon ">
            <span class="fa-stack">
              <i class="fa-solid fa-circle-plus"></i>
            </span>
          </div>
          <div class="footer-text">
            新規作成
          </div>
        <% end %>
      </div>
      <div class="footer-bg">
        <%= link_to new_user_registration_path do %>
          <div class="footer-icon ">
            <span class="fa-stack">
              <i class="fa-solid fa-right-to-bracket"></i>
            </span>
          </div>
          <div class="footer-text">
            会員登録
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="d-flex justify-content-around">
    <div class="text-center header-bg">
      <%= link_to "つかいかた", about_path, class: "header-text" %>
    </div>
    <!--admin signed in-->
    <% if admin_signed_in? %>
      <h1>
        <%= link_to admin_top_path do %>
          <div class="excelloon-icon d-block mx-auto"></div>
        <% end %>
      </h1>
      <div class="text-center header-bg">
        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "header-text" %>
      </div>
    <!--user signed in-->
    <% elsif user_signed_in? %>
      <h1>
        <%= link_to root_path do %>
          <div class="excelloon-icon d-block mx-auto"></div>
        <% end %>
      </h1>
      <div class="text-center header-bg">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-text" %>
      </div>
    <!--guest-->
    <% else %>
      <h1>
        <%= link_to root_path do %>
          <div class="excelloon-icon d-block mx-auto"></div>
        <% end %>
      </h1>
      <div class="text-center header-bg">
        <%= link_to 'ログイン', new_user_session_path, class: "header-text" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>えくせるーん -Excellent Balloon-</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <script src="https://kit.fontawesome.com/<%= ENV['FONT_AWESOME_CODE'] %>.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/header" %>
    </div>

    <div class="text-center">
      <%= render 'layouts/flash' %>
    </div>
    <div class="pb-5">
      <%= yield %>
    </div>

    <div class="container-fluid">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>